server:
  port: 8082
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB

spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: audio-processing-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/Smart-Exam-Monitoring
##          jwk-set-uri: http://localhost:8080/realms/Smart-Exam-Monitoring/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /audio-processing-service/v3/api-docs
  swagger-ui:
    path: /audio-processing-service/swagger-ui.html