logging:
  level:
    root: DEBUG
spring:
  datasource:
    username: yaphet
    password: root
    url: jdbc:postgresql://localhost:5432/exam_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
