spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

sentry:
  dsn: https://efca1a8038b74398be7d4dfa04720b74@o1356916.ingest.sentry.io/4505108545011712
  traces-sample-rate: 1.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/