server:
  port: 8761
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false