name: Run Docker-Compose in CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Run Container
        run: docker-compose up -d
      - name: Publish Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'target/test-results/test/TEST-*.xml'
